### ISSUE TITLE
have a trubble 

### ISSUE THREAD

**Issue by laodaobazi** [1and1/cosmo#2]
hi man when in cosmo-cosmo-multimodule-0.94 dir run "mvn tomcat7:run-war -Dmaven.test.skip=true" ,build seccess .like this:
[INFO] cosmo-multimodule .................................. SUCCESS [  7.780 s]
[INFO] cosmo-api .......................................... SUCCESS [  1.820 s]
[INFO] cosmo-core ......................................... SUCCESS [  3.946 s]

BUT in cosmo-cosmo-multimodule-0.94/cosmo-webapp dir run "mvn tomcat7:run-war -Dmaven.test.skip=true" have a problem .like this :

Dec 15, 2015 11:40:32 PM org.springframework.web.context.ContextLoader initWebApplicationContext
SEVERE: Context initialization failed
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at org.unitedinternet.cosmo.servletcontext.ServletContextUtil.extractApplicationProperties(ServletContextUtil.java:31)
	at org.unitedinternet.cosmo.servletcontext.CosmoApplicationContextInitializer.initialize(CosmoApplicationContextInitializer.java:21)
	at org.unitedinternet.cosmo.servletcontext.CosmoApplicationContextInitializer.initialize(CosmoApplicationContextInitializer.java:13)
	at org.springframework.web.context.ContextLoader.customizeContext(ContextLoader.java:450)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:402)

what happened? what can I do?  can you help me , thanks!

**Comment by corneliudobrota** [comment]
Hi laodaobazi,

This should be fixed now. 
Please note that being just a demo app, cosmo-webapp is not part of multiproject anymore.
You should run ```mvn clean install```  in the cosmo directory. 
After the install is performed, please run ```mvn tomcat7:run-war``` in the cosmo/cosmo-webapp directory.

Regards,
Cornel

**Comment by laodaobazi** [comment]
I'm sorry  I think that in my workspace maybe missing a properties file .first run <b>mvn clean install</b> then run <b>mvn tomcat7:run-war</b>.the problem also ,like that:
INFO: Initializing Spring root WebApplicationContext
Dec 16, 2015 5:52:54 AM org.springframework.web.context.ContextLoader initWebApplicationContext
INFO: Root WebApplicationContext: initialization started
Dec 16, 2015 5:52:54 AM org.springframework.web.context.ContextLoader initWebApplicationContext
SEVERE: Context initialization failed
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at org.unitedinternet.cosmo.servletcontext.ServletContextUtil.extractApplicationProperties(ServletContextUtil.java:31)
	at org.unitedinternet.cosmo.servletcontext.CosmoApplicationContextInitializer.initialize(CosmoApplicationContextInitializer.java:21)
	at org.unitedinternet.cosmo.servletcontext.CosmoApplicationContextInitializer.initialize(CosmoApplicationContextInitializer.java:13)
	at org.springframework.web.context.ContextLoader.customizeContext(ContextLoader.java:450)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:402)

Can you give me a cosmo.war by Email ( the email address is 06libiao@sina.com )?
